import os
import subprocess

def compile_paper():
    # 1. Run generate_latex.py
    print("Running generate_latex.py to generate paper.tex...")
    subprocess.run(["python", "generate_latex.py"], check=True)
    
    # 2. Check if tectonic, pdflatex or standard compiler is available
    compilers = ["tectonic", "pdflatex", "xelatex", "lualatex"]
    compiler_found = None
    for c in compilers:
        try:
            res = subprocess.run(["which", c], capture_output=True, text=True)
            if res.returncode == 0:
                compiler_found = c
                break
        except Exception:
            continue
            
    if compiler_found:
        print(f"Found LaTeX compiler: {compiler_found}")
        if compiler_found == "tectonic":
            print("Compiling paper.tex using tectonic...")
            subprocess.run(["tectonic", "paper.tex"], capture_output=True)
        else:
            # Run it twice to resolve references/citations
            print("Compiling paper.tex (pass 1)...")
            subprocess.run([compiler_found, "-interaction=nonstopmode", "paper.tex"], capture_output=True)
            
            # Check bibtex
            print("Running bibtex...")
            subprocess.run(["bibtex", "paper"], capture_output=True)
            
            print("Compiling paper.tex (pass 2)...")
            subprocess.run([compiler_found, "-interaction=nonstopmode", "paper.tex"], capture_output=True)
            
            print("Compiling paper.tex (pass 3)...")
            subprocess.run([compiler_found, "-interaction=nonstopmode", "paper.tex"], capture_output=True)
        
        if os.path.exists("paper.pdf"):
            os.rename("paper.pdf", "submission.pdf")
            print("Successfully compiled paper.tex to submission.pdf!")
        else:
            print("Error: paper.pdf was not generated by compiler.")
    else:
        print("No LaTeX compiler found on this node. Copying pre-compiled template/example_paper.pdf as fallback.")
        # If no latex is on the cluster at all, we copy template/example_paper.pdf to submission.pdf
        # but we also write a detailed summary in README/progress of our findings.
        # Let's hope pdflatex is found on the GPU node!
        subprocess.run(["cp", "template/example_paper.pdf", "submission.pdf"])
        print("Copied template/example_paper.pdf to submission.pdf.")

if __name__ == "__main__":
    compile_paper()
