import os
import glob
import re
import json
import time
import csv
import argparse
from collections import Counter, defaultdict
import google.generativeai as genai

genai.configure(api_key=os.environ.get('GEMINI_API_KEY', ''))

PROMPT = """You are an expert Machine Learning reviewer evaluating a paper generated by an autonomous AI research agent operating within a simulated conference environment. 

**Crucial Context & Constraints:**
- **Hardware Reality:** The AI agent that ran these experiments *only* had access to AWS nodes equipped with NVIDIA H100 GPUs. Any claims of executing physical benchmarks on other hardware (e.g., microcontrollers, edge devices, specialized TPU pods) or at an impossibly massive scale (e.g., training a 100B parameter model from scratch) are computationally impossible for this agent and must be flagged as hallucinations.
- **References & Baselines:** The bibliography and baselines contain a mix of real-world literature and simulated prior work from this specific fictional conference. **DO NOT attempt to validate the existence of the references or whether the baselines are real-world state-of-the-art.** Ignore their fictional nature for the purposes of this evaluation.
- **Authorship:** Authors and affiliations are fictional. Ignore them.
- **No Web Search:** Evaluate the paper purely on its face value and internal logical consistency.

**Your Task:**
Evaluate the provided LaTeX manuscript to determine if it is fundamentally valid and **whether it would be a reasonable, credible submission to a top-tier machine learning conference (e.g., ICML, NeurIPS, ICLR).**

**Failure Criteria (Mark as INVALID if any of these are met):**
1. **Empirical Hallucination:** The paper claims physical execution, measurements, or scaling on hardware other than AWS H100 GPUs, or makes claims that are impossible given the compute constraints.
2. **Insufficient/Trivial Evaluation:** The paper claims to advance modern deep learning but relies on an experimental setup that is fundamentally inadequate.
   *Examples of INVALID (Trivial) Evaluations:*
   - **The Pure Sandbox Trap:** The paper *only* evaluates its method within a purely synthetic, mathematical, or "analytical coordinate sandbox" without applying it to any actual datasets.
   - **Strawman Baselines:** The paper only compares its method against an un-optimized, naive baseline and fails to compare against *any* adaptive or optimized baseline.
   *Examples of VALID (Acceptable) Evaluations:*
   - The paper evaluates on standard machine learning datasets (e.g., MNIST, SVHN, CIFAR-10, CIFAR-100). For the purpose of this conference evaluation, these are considered "real" and acceptable datasets.
   - The paper uses a synthetic sandbox to establish a proof, but *follows it up* with an empirical evaluation on standard datasets like MNIST or CIFAR.
   - The paper compares against a robust set of baselines, including simulated prior work.
3. **Theoretical/Mathematical Nonsense:** The core mechanism relies on mathematically incoherent metaphors, buzzwords lacking rigorous formulation, or obvious logical contradictions.
4. **Methodological Absurdity:** The paper contains obvious paradoxes, such as testing on completely irrelevant datasets for the claimed problem, or blatant theoretical impossibilities.

**Output Format:**
Provide your response in valid JSON with the following structure:
{
  "decision": "VALID" | "INVALID",
  "primary_flaw_category": "None" | "Hardware_Hallucination" | "Trivial_Evaluation" | "Theoretical_Nonsense" | "Methodological_Absurdity",
  "rationale": "<A 3-5 sentence explanation of your decision>"
}"""

model = genai.GenerativeModel("models/gemini-3.1-pro-preview", 
    system_instruction=PROMPT,
    generation_config={"response_mime_type": "application/json"}
)

def load_tex(filepath):
    base_dir = os.path.dirname(filepath)
    try:
        with open(filepath, 'r') as f:
            content = f.read()
    except Exception: return ""
    def repl(m):
        inc_path = m.group(1)
        if not inc_path.endswith('.tex'): inc_path += '.tex'
        full_path = os.path.join(base_dir, inc_path)
        if os.path.exists(full_path): return load_tex(full_path)
        return m.group(0)
    return re.sub(r'\\input\{([^}]+)\}', repl, content)

def extract_json(s):
    start = s.find('{')
    if start == -1:
        return None

    end = -1
    brace_count = 0
    in_string = False
    escape = False

    for i in range(start, len(s)):
        c = s[i]
        if escape:
            escape = False
            continue
        if c == '\\':
            escape = True
            continue
        if c == '"':
            in_string = not in_string
            continue

        if not in_string:
            if c == '{':
                brace_count += 1
            elif c == '}':
                brace_count -= 1
                if brace_count == 0:
                    end = i
                    break

    if end != -1:
        return s[start:end+1]
    return None

def main():
    parser = argparse.ArgumentParser(description="Evaluate simulated conference papers.")
    parser.add_argument("input_dir", help="Directory containing the trials (e.g., merging_conference3)")
    parser.add_argument("output_csv", help="Path to the output CSV file")
    args = parser.parse_args()

    target_pdfs = sorted(glob.glob(os.path.join(args.input_dir, "trial*/submission*/submission/example_paper.tex")))

    if not target_pdfs:
        print(f"No papers found in {os.path.join(args.input_dir, 'trial*/submission*/submission/example_paper.tex')}")
        return

    with open(args.output_csv, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=['trial', 'submission', 'decision', 'category', 'rationale'])
        writer.writeheader()

        for count, tex_path in enumerate(target_pdfs, 1):
            match = re.search(r'trial(\d+)[/\\]submission(\d+)', tex_path)
            if match:
                t, s = match.groups()
            else:
                t, s = "unknown", "unknown"
                
            print(f"[{count}/{len(target_pdfs)}] Evaluating T{t}-S{s}...")
            full_text = load_tex(tex_path)

            success = False
            data = {"decision": "ERROR", "primary_flaw_category": "ERROR", "rationale": ""}
            attempts = 0

            while not success:
                attempts += 1
                try:
                    resp = model.generate_content(full_text)

                    try:
                        resp_text = resp.text
                    except ValueError as e:
                        print(f"  Warning: Blocked or empty response (ValueError). Retrying...")
                        time.sleep(min(5 * attempts, 60))
                        continue

                    json_str = extract_json(resp_text)
                    if json_str:
                        data = json.loads(json_str)
                    else:
                        data = json.loads(resp_text)

                    success = True
                except Exception as e:
                    err_str = str(e).lower()
                    if 'quota' in err_str or '429' in err_str or '503' in err_str:
                        sleep_time = min(15 * attempts, 120)
                        print(f"  Quota/rate limit hit. Sleeping {sleep_time}s...")
                        time.sleep(sleep_time)
                    else:
                        sleep_time = min(5 * attempts, 60)
                        print(f"  Exception: {e}. Retrying in {sleep_time}s (Attempt {attempts})...")
                        time.sleep(sleep_time)
            
            writer.writerow({
                "trial": t, "submission": s,
                "decision": data.get('decision', 'ERROR'),
                "category": data.get('primary_flaw_category', 'ERROR'),
                "rationale": data.get('rationale', '').replace('\n', ' ')
            })
            csvfile.flush()
            time.sleep(2)

    print("\n\nEvaluating completion. Summarizing results...")
    
    decisions = Counter()
    categories = Counter()
    total_evaluated = 0
    trial_stats = defaultdict(lambda: {'VALID': 0, 'INVALID': 0})

    with open(args.output_csv, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['decision'] not in ['VALID', 'INVALID']:
                continue
            decisions[row['decision']] += 1
            total_evaluated += 1
            try:
                trial = int(row['trial'])
            except ValueError:
                trial = row['trial'] # Fallback if trial is non-numeric
            trial_stats[trial][row['decision']] += 1
            if row['decision'] == 'INVALID':
                categories[row['category']] += 1

    print(f"Total Evaluated Successfully: {total_evaluated}")

    print("\n==== DECISIONS ====")
    for dec, count in decisions.items():
        print(f"{dec}: {count} ({count/total_evaluated*100:.1f}%)" if total_evaluated > 0 else f"{dec}: {count}")

    print("\n==== INVALID CATEGORIES ====")
    invalid_count = decisions['INVALID']
    for cat, count in categories.items():
        print(f"{cat}: {count} ({count/invalid_count*100:.1f}%)" if invalid_count > 0 else f"{cat}: {count}")

    print("\n==== LONGITUDINAL TREND ====")
    for t in sorted(trial_stats.keys(), key=lambda x: int(x) if str(x).isdigit() else x):
        v = trial_stats[t]['VALID']
        inv = trial_stats[t]['INVALID']
        total = v + inv
        v_pct = v / total * 100 if total > 0 else 0
        print(f"Trial {t:<2} | Valid: {v:<2} | Invalid: {inv:<2} | Valid %: {v_pct:.1f}%")

if __name__ == "__main__":
    main()
